spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:lpsearch-mysql-core}:${MYSQL_PORT:3306}/lpsearch_core?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  redis:
    host: ${REDIS_HOST:lpsearch-redis}
    port: ${REDIS_PORT:6379}
    # 커넥션 타임아웃 설정
    connect-timeout: 5s
    timeout: 5s
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 100ms
  cache:
    type: redis
  sql:
    init:
      mode: always
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui
      operations-sorter: method

jwt:
  secret: ${JWT_SECRET:your-secret-key-here-must-be-at-least-256-bits-long}
  expiration: ${JWT_EXPIRATION:86400000} # 24시간
