spring:
  datasource:
    url: jdbc:h2:~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  cache:
    type: redis
