
services:
  app:
    build:
      context: ./backend/lpsearch-backend
      dockerfile: Dockerfile
    image: lpsearch-backend:latest  
    container_name: lpsearch-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  redis:
    image: redis:7-alpine
    container_name: lpsearch-redis
    ports:
      - "6379:6379"

