version: "3.8"

services:
  lpsearch-gateway:
    build:
      context: ./backend/api-gateway
    ports:
      - "8888:8888"
    depends_on:
      - lpsearch-core-api
      - lpsearch-board-api
    restart: unless-stopped
  lpsearch-board-api:
    build:
      context: ./backend/node-server
    container_name: lpsearch-board-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MYSQL_HOST=lpsearch-mysql-board
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=lpsearch_board
      - REDIS_HOST=lpsearch-redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_jwt_secret_key
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - lpsearch-mysql-board
      - lpsearch-redis
    restart: unless-stopped
  lpsearch-core-api:
    build:
      context: ./backend/lpsearch-backend/lpsearch-backend
      dockerfile: Dockerfile
    image: lpsearch-backend:latest
    container_name: lpsearch-core-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://lpsearch-mysql-core:3306/lpsearch_core?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_REDIS_HOST=lpsearch-redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - lpsearch-redis
      - lpsearch-mysql-core
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lpsearch-frontend
    ports:
      - "3000:80"
    depends_on:
      - lpsearch-core-api
      - lpsearch-board-api
    restart: unless-stopped
  lpsearch-redis:
    image: redis:7-alpine
    container_name: lpsearch-redis
    ports:
      - "6379:6379"
    restart: always

  lpsearch-mysql-core:
    image: mysql:8
    container_name: lpsearch-mysql-core
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: lpsearch_core
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  lpsearch-mysql-board:
    image: mysql:8
    container_name: lpsearch-mysql-board
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: lpsearch_board

volumes:
  mysql-data:
